# Copyright (c) 2026 llm-bench authors
# SPDX-License-Identifier: MIT
"""Result reporting utilities.

Generates a summarised HTML dashboard for benchmark runs from SQLite
historical data. Supports multi-model comparison with Chart.js charts,
expandable score tables, and per-sample detail modals.
"""

import json
from pathlib import Path
from typing import Any

from loguru import logger

from llm_bench.storage import BenchmarkDB


def _build_html(
    models: list[str],
    chart_json: str,
    scores_json: str,
    samples_json: str,
    bench_names: dict[str, str],
) -> str:
    """Build the complete HTML report string.

    Args:
        models: List of model identifiers.
        chart_json: JSON string with chart data.
        scores_json: JSON string with all score data.
        samples_json: JSON string with per-sample data.
        bench_names: Mapping of benchmark keys to display names.

    Returns:
        Complete HTML document string.
    """
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Benchmark Report — Multi-Model Comparison</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<style>
  :root {{--bg:#fff;--fg:#1a1a2e;--accent:#4f46e5;--muted:#6b7280;--border:#e5e7eb;}}
  * {{box-sizing:border-box;margin:0;padding:0;}}
  body {{
    font-family:system-ui,-apple-system,sans-serif;
    background:var(--bg);color:var(--fg);
    line-height:1.6;padding:2rem;
  }}
  .container {{max-width:1200px;margin:0 auto;}}
  h1 {{font-size:1.75rem;margin-bottom:0.5rem;}}
  .subtitle {{color:var(--muted);margin-bottom:2rem;}}
  .card {{
    background:#f8fafc;border-radius:0.75rem;
    padding:1.5rem;margin-bottom:1.5rem;
    box-shadow:0 1px 3px rgba(0,0,0,0.05);
  }}
  .card h2 {{font-size:1.125rem;margin-bottom:1rem;color:var(--accent);}}
  canvas {{max-height:400px;}}
  table {{
    width:100%;border-collapse:collapse;margin-top:0.5rem;
    font-size:0.875rem;
  }}
  th,td {{padding:0.5rem 0.75rem;text-align:left;border-bottom:1px solid var(--border);}}
  th {{background:#f1f5f9;font-weight:600;position:sticky;top:0;}}
  tr:hover {{background:#f8fafc;}}
  .clickable {{cursor:pointer;user-select:none;}}
  .clickable:hover {{color:var(--accent);}}
  .details {{display:none;margin-top:0.5rem;}}
  .details.open {{display:block;}}
  .toggle-icon {{display:inline-block;width:1em;transition:transform 0.2s;}}
  .toggle-icon.open {{transform:rotate(90deg);}}
  .badge {{
    display:inline-block;padding:0.125rem 0.5rem;
    border-radius:9999px;font-size:0.75rem;font-weight:600;
  }}
  .badge-green {{background:#d1fae5;color:#065f46;}}
  .badge-yellow {{background:#fef3c7;color:#92400e;}}
  .badge-red {{background:#fee2e2;color:#991b1b;}}
  .modal-overlay {{
    display:none;position:fixed;top:0;left:0;right:0;bottom:0;
    background:rgba(0,0,0,0.5);z-index:1000;
    justify-content:center;align-items:center;
  }}
  .modal-overlay.open {{display:flex;}}
  .modal {{
    background:white;border-radius:0.75rem;padding:1.5rem;
    max-width:90vw;max-height:85vh;overflow:auto;
    min-width:600px;box-shadow:0 20px 60px rgba(0,0,0,0.3);
  }}
  .modal h3 {{margin-bottom:1rem;}}
  .modal-close {{
    float:right;background:none;border:none;font-size:1.5rem;
    cursor:pointer;color:var(--muted);
  }}
  .modal-close:hover {{color:var(--fg);}}
  .sample-table {{font-size:0.8rem;}}
  .sample-table td {{max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}}
  .sample-table td.expanded {{white-space:normal;word-break:break-all;}}
  .model-select {{
    padding:0.5rem;border:1px solid var(--border);border-radius:0.5rem;
    font-size:0.875rem;margin-bottom:1rem;
  }}
</style>
</head>
<body>
<div class="container">
  <h1>LLM Benchmark Report</h1>
  <p class="subtitle">Multi-model comparison · Generated by llm-bench</p>

  <div class="card">
    <h2>Model Comparison</h2>
    <label for="modelSelect">Models:</label>
    <select id="modelSelect" class="model-select" multiple>
      {"".join(f'<option value="{m}" selected>{m}</option>' for m in models)}
    </select>
    <canvas id="comparisonChart"></canvas>
  </div>

  <div id="benchmarkCards"></div>
</div>

<!-- Sample Detail Modal -->
<div id="sampleModal" class="modal-overlay">
  <div class="modal">
    <button class="modal-close" onclick="closeModal()">&times;</button>
    <h3 id="modalTitle">Sample Details</h3>
    <div id="modalContent"></div>
  </div>
</div>

<script>
const CHART_DATA = {chart_json};
const SCORES = {scores_json};
const SAMPLES = {samples_json};
const BENCH_NAMES = {json.dumps(bench_names)};

const COLORS = ['#4f46e5','#06b6d4','#10b981','#f59e0b','#ec4899','#8b5cf6','#ef4444','#14b8a6'];

function getBadge(accuracy) {{
  if (accuracy >= 80) return '<span class="badge badge-green">' + accuracy.toFixed(1) + '%</span>';
  if (accuracy >= 50) return '<span class="badge badge-yellow">' + accuracy.toFixed(1) + '%</span>';
  return '<span class="badge badge-red">' + accuracy.toFixed(1) + '%</span>';
}}

function renderChart() {{
  const selected = Array.from(document.getElementById('modelSelect').selectedOptions).map(o => o.value);
  const benchmarks = Object.keys(BENCH_NAMES);
  const labels = benchmarks.map(b => BENCH_NAMES[b] || b);

  const datasets = selected.map((model, i) => ({{
    label: model,
    data: benchmarks.map(b => (CHART_DATA[model] && CHART_DATA[model][b]) || 0),
    backgroundColor: COLORS[i % COLORS.length],
    borderRadius: 6,
  }}));

  const ctx = document.getElementById('comparisonChart');
  if (window._chart) window._chart.destroy();
  window._chart = new Chart(ctx, {{
    type: 'bar',
    data: {{ labels, datasets }},
    options: {{
      responsive: true,
      maintainAspectRatio: false,
      scales: {{
        y: {{
          beginAtZero: true,
          max: 100,
          title: {{ display: true, text: 'Score / Accuracy (%)' }}
        }}
      }},
      plugins: {{
        legend: {{ display: selected.length > 1 }}
      }}
    }}
  }});
}}

function renderCards() {{
  const container = document.getElementById('benchmarkCards');
  container.innerHTML = '';

  for (const [bench, displayName] of Object.entries(BENCH_NAMES)) {{
    const modelsData = SCORES[bench];
    if (!modelsData) continue;

    const card = document.createElement('div');
    card.className = 'card';

    // Collect all categories across models
    const allCats = new Set();
    for (const model of Object.keys(modelsData)) {{
      for (const cat of Object.keys(modelsData[model])) {{
        allCats.add(cat);
      }}
    }}
    const categories = Array.from(allCats).sort((a, b) => {{
      if (a === 'overall') return -1;
      if (b === 'overall') return 1;
      return a.localeCompare(b);
    }});

    let tableHtml = '<table><thead><tr><th>Category</th>';
    for (const model of Object.keys(modelsData)) {{
      tableHtml += '<th>' + model + '</th>';
    }}
    tableHtml += '</tr></thead><tbody>';

    for (const cat of categories) {{
      const isOverall = cat === 'overall';
      tableHtml += '<tr' + (isOverall ? ' style="font-weight:600"' : '') + '>';
      tableHtml += '<td>' + cat + '</td>';
      for (const model of Object.keys(modelsData)) {{
        const entry = modelsData[model][cat];
        if (entry) {{
          const acc = entry.accuracy || 0;
          let cell = getBadge(acc);
          if (entry.correct != null && entry.total != null) {{
            cell += ' <span style="color:var(--muted);font-size:0.75rem">(' + entry.correct + '/' + entry.total + ')</span>';
          }}
          tableHtml += '<td>' + cell + '</td>';
        }} else {{
          tableHtml += '<td>—</td>';
        }}
      }}
      tableHtml += '</tr>';
    }}
    tableHtml += '</tbody></table>';

    // Add sample detail links
    let sampleLinks = '<div style="margin-top:0.75rem">';
    for (const model of Object.keys(modelsData)) {{
      if (SAMPLES[model] && SAMPLES[model][bench]) {{
        sampleLinks += '<button onclick="showSamples(\\'' + model + '\\',\\'' + bench + '\\')" ';
        sampleLinks += 'style="margin-right:0.5rem;padding:0.25rem 0.75rem;border:1px solid var(--border);';
        sampleLinks += 'border-radius:0.375rem;background:white;cursor:pointer;font-size:0.8rem">';
        sampleLinks += '\U0001f4cb ' + model + ' samples</button>';
      }}
    }}
    sampleLinks += '</div>';

    card.innerHTML = '<h2>' + displayName + '</h2>' + tableHtml + sampleLinks;
    container.appendChild(card);
  }}
}}

function showSamples(model, bench) {{
  const samples = SAMPLES[model] && SAMPLES[model][bench];
  if (!samples) return;

  document.getElementById('modalTitle').textContent = model + ' — ' + (BENCH_NAMES[bench] || bench) + ' Samples';

  // Build sample table
  const keys = Object.keys(samples[0]).filter(k => k !== 'sample_id' && k !== 'response' && k !== 'context');
  let html = '<div style="margin-bottom:0.5rem;color:var(--muted);font-size:0.8rem">' + samples.length + ' samples</div>';
  html += '<table class="sample-table"><thead><tr><th>#</th>';
  for (const k of keys) {{
    html += '<th>' + k + '</th>';
  }}
  html += '<th>response</th></tr></thead><tbody>';

  for (let i = 0; i < samples.length; i++) {{
    const s = samples[i];
    html += '<tr><td>' + (i + 1) + '</td>';
    for (const k of keys) {{
      let val = s[k];
      if (typeof val === 'boolean') val = val ? '\\u2713' : '\\u2717';
      else if (val === null || val === undefined) val = '—';
      else if (typeof val === 'object') val = JSON.stringify(val);
      else val = String(val);
      html += '<td title="' + val.replace(/"/g, '&quot;') + '">' + val + '</td>';
    }}
    const resp = s.response || '';
    html += '<td title="' + resp.replace(/"/g, '&quot;').substring(0, 200) + '">' + resp.substring(0, 100) + (resp.length > 100 ? '\\u2026' : '') + '</td>';
    html += '</tr>';
  }}
  html += '</tbody></table>';

  document.getElementById('modalContent').innerHTML = html;
  document.getElementById('sampleModal').classList.add('open');
}}

function closeModal() {{
  document.getElementById('sampleModal').classList.remove('open');
}}

document.getElementById('sampleModal').addEventListener('click', function(e) {{
  if (e.target === this) closeModal();
}});

document.getElementById('modelSelect').addEventListener('change', renderChart);

// Initial render
renderChart();
renderCards();
</script>
</body>
</html>"""


def generate_html_report(db: BenchmarkDB, out_dir: Path) -> None:
    """Render a multi-model comparison HTML report from SQLite data.

    Generates a self-contained HTML file with:
    - Bar chart comparing models across benchmarks
    - Expandable per-benchmark score tables
    - Per-sample detail modal

    Args:
        db: Open database connection with historical data.
        out_dir: Directory where ``benchmark_report.html`` will be
            written.
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    # Gather data from DB
    models = db.query_models()
    all_scores = db.query_all_scores()

    # Build structured data: benchmark -> model -> category -> score row
    benchmark_data: dict[str, dict[str, dict[str, Any]]] = {}
    for row in all_scores:
        bench = row["benchmark"]
        model = row["model"]
        cat = row["category"]
        benchmark_data.setdefault(bench, {}).setdefault(model, {})[cat] = row

    # Compute overall averages per model per benchmark for the chart
    chart_entries: dict[str, dict[str, float]] = {}
    for bench, models_data in benchmark_data.items():
        for model, cats in models_data.items():
            if "overall" in cats:
                avg = cats["overall"]["accuracy"] or 0.0
            else:
                vals = [
                    c["accuracy"] for c in cats.values() if c["accuracy"] is not None
                ]
                avg = sum(vals) / len(vals) if vals else 0.0
            chart_entries.setdefault(model, {})[bench] = round(avg, 2)

    # Prepare JSON data for the HTML
    chart_json = json.dumps(chart_entries)
    scores_json = json.dumps(benchmark_data)

    # Build sample data per model+benchmark
    sample_data: dict[str, dict[str, list[dict[str, Any]]]] = {}
    for model in models:
        benchmarks = db.query_benchmarks(model)
        for bench in benchmarks:
            samples = db.query_samples(model, bench)
            if samples:
                sample_data.setdefault(model, {})[bench] = samples
    samples_json = json.dumps(sample_data, ensure_ascii=False)

    # Benchmark display names
    bench_names = {
        "lveval": "LVEval",
        "longbench": "LongBench-v2",
        "matharena": "MathArena",
        "bfcl": "BFCL v4",
        "simplevqa": "SimpleVQA",
        "comparebench": "CompareBench",
    }

    html = _build_html(
        models=models,
        chart_json=chart_json,
        scores_json=scores_json,
        samples_json=samples_json,
        bench_names=bench_names,
    )

    report_path = out_dir / "benchmark_report.html"
    report_path.write_text(html, encoding="utf-8")
    logger.info("Report saved to {}", report_path)
